name: spikable2
description: spikable2 to make rapid initial development environment with null safety.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
    
  # A package for manipulating stack traces and printing them readably.
  stack_trace: ^1.10.0

  # Default icons asset for Cupertino widgets based on Apple styled icons.
  cupertino_icons: ^1.0.2

  # Flutter plugin for getting commonly used locations on host platform file systems, 
  # such as the temp and app data directories.
  path_provider: ^2.0.1

  # Flutter package that allows setting the web app URL strategy with a single line of code.
  url_strategy: ^0.2.0

  # A fast, extra light and synchronous key-value storage written entirely in Dart
  get_storage: ^2.0.2

  # Open screens/snackbars/dialogs without context, manage states and 
  # inject dependencies easily with GetX.
  get: ^4.1.2

  # Provides APIs for debugging and error logging. 
  # This library introduces abstractions similar to those used in other languages, 
  # such as the Closure JS Logger and java.util.logging.Logger.
  logging: ^1.0.1

  # An abstract class that helps to implement equality without needing to 
  # explicitly override == and hashCode.
  equatable: ^2.0.0

  # A wrapper around InheritedWidget to make them easier to use and more reusable.
  provider: ^5.0.0

  # A package to include fonts from fonts.google.com in your Flutter app.
  google_fonts: ^2.0.0

  # Easily make Flutter apps responsive. Automatically adapt UI to different screen sizes. 
  # Responsiveness made simple.
  responsive_framework: ^0.1.0

  # Fancy pre-built animations that can easily be integrated into any Flutter application.
  animations: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
